Wargus/stratagus

debian/copyright

this silence a lintian false positive
feel free to add yourself

debian: rewrite copyright in machine-readable format

---

src/sound/sound_server.cpp

-- Sound server now uses a thread to avoid mixing the buffers inside the sdl callback.
Hi, I've added a thread for the sound server, so that the callback doesn't need to process all the mixing from sounds and music.
I've tested it on linux and mac.
Regards,
Marcelo

Added thread on sound server

---

src/video/sdl.cpp

Fullscreen is toggled fine now on OSX

---

src/sound/sound_server.cpp

This fixes two issues that was encountered with the new audio thread code while testing with Wyrmsun:
- Fixed deadlock within the sound system
- Fixed issue on windows only that made the audio sluggish

Fixes deadlock and issue on windows with audio system

---

src/include/video.h
src/video/graphic.cpp
src/video/intern_video.h
src/video/video.cpp

Fixes #147 (and also https://github.com/Andrettin/Wyrmgus/issues/27)

Force re-generating the textures for color cycled graphics in OpenGL

---

src/ai/ai_plan.cpp
src/stratagus/script.cpp

Using Linux (CentOS 7) cause an error, when compiling Tag 2.4.

Fix #205 unable to find string literal operator operator"" _C_

---

cmake/modules/FindSqlite.cmake
metaserver/db.cpp
src/ai/ai_force.cpp

Metaserver does not start up #227

Metaserver fix

---

.gitignore
src/stratagus/script.cpp
src/video/graphic.cpp

I created the code to adapt stratagus to lua 5.2 and 5.3. While it should keep the compatibility with 5.1 I cannot test it, so I ask you to test it before in your machines.

Adaptation to Lua 5.3

---

src/ai/ai_force.cpp
src/include/stratagus.h
src/include/util.h

Incorporate a couple of fixes from Wyrmgus

---

src/include/unitsound.h
src/sound/sound.cpp
src/sound/unitsound.cpp
src/unit/script_unittype.cpp

Part 1 to fix https://github.com/Wargus/wargus/issues/296

Support setting a work-complete sound per unit type

---

src/editor/edmap.cpp

Fixes tiling issue when placing forest in dark water and similar situations involving dark water, dark grass or forests being placed on water.
May cause some organic growth of coasts.
It's possible that the real problem exists somewhere below tileFromQuad, but I couldn't figure it out.
To reproduce the issue:
Make a large body of dark water.
Try placing a forest tile in the middle.
On my computer, this results in a cascading tiling error.
Only tested with wargus (BNE version on Linux).

let EditorChangeSurrounding recurse until done

---

src/game/game.cpp
src/include/ui.h
src/ui/interface.cpp
src/ui/mouse.cpp
src/ui/ui.cpp
src/unit/unit.cpp
src/video/cursor.cpp

in wargus, this means watching 2 computers fight eachother.
any interaction will end the demo.
Could also create a IsDemoMode() helper instead of the "weird?" (GameRunning && ThisPlayer->Type == PlayerNobody) check.
The term demo is a bit confusing here though, as it has nothing to do with the shareware version.

add minimal support for attract/demo mode

---

CMakeLists.txt
src/action/action_explore.cpp
src/action/actions.cpp
src/action/command.cpp
src/game/replay.cpp
src/include/action/action_explore.h
src/include/actions.h
src/include/commands.h
src/include/interface.h
src/include/net_message.h
src/include/ui.h
src/network/commands.cpp
src/ui/botpanel.cpp
src/ui/popup.cpp
src/ui/script_ui.cpp

flies around randomly, much room for improvement
You can test it in wargus by adding a button for it, like so in scripts/human/buttons.lua:
DefineButton( { Pos = 3, Level = 0, Icon = "icon-human-patrol-naval",
Action = "explore",
Key = "x", Hint = _("E~!XPLORE"), Popup = "popup-human-commands",
ForUnit = {"unit-balloon"} }
Not sure what is supposed to be written in the copyright section. Let me know if I messed up.

add a simple explore action

---

src/action/action_built.cpp
src/action/action_train.cpp
src/game/game.cpp
src/include/unittype.h
src/unit/script_unit.cpp
src/unit/script_unittype.cpp
src/unit/unittype.cpp

* add OnReady luacallback for units
* allow setting TTL, Summoned variables on units
* allow issuing the explore action on units with OrderUnit
( my last pull request in stratagus for a short while, I promise : - )

Add some more lua bindings

---

src/include/spells.h
src/spell/spells.cpp
src/ui/mouse.cpp

This is mainly for my own amusement.
But, in theory this could be used to implement autocast for holy vision and floating eye in wargus.

allow self-cast if enabled, default is disabled

---

src/video/sdl.cpp

fix for this issue: https://github.com/Wargus/stratagus/issues/263

opengl crash on video playback fixed

---

src/ui/mainscr.cpp

Improvement for this PR https://github.com/Wargus/stratagus/pull/267
Using an std::string instead of increasing buffersize.

Update to the displayed number of extra selected units.

---

src/action/action_attack.cpp

There was an issue - a unit which attacks wall, will attack it and after wall being destroyed. There wasn't a condition check for wall destroyed. This PR fix this.

Fixup for wall attack.

---

src/guichan/include/guichan/image.h
src/guichan/include/guichan/widgets/icon.h
src/guichan/widgets/icon.cpp
src/include/movie.h
src/include/video.h
src/tolua/stratagus.pkg
src/tolua/ui.pkg
src/tolua/video.pkg
src/video/mng.cpp
src/video/movie.cpp

Make MNGs and Ogg movies available as guichan images which can be put inside ImageWidgets

Animated widgets

---

src/network/online_service.cpp

```
../stratagus/src/network/online_service.cpp: In member function ‘void Context::setPassword(std::string)’:
[build] ../stratagus/src/network/online_service.cpp:1215:35: error: iteration 5 invokes undefined behavior [-Werror=aggressive-loop-optimizations]
[build]  1215 |                 this->password[i] = 0;
[build]       |                 ~~~~~~~~~~~~~~~~~~^~~
[build] /../stratagus/src/network/online_service.cpp:1214:31: note: within this loop
[build]  1214 |             for (int i = 0; i < sizeof(password); i++) {
[build]       |                             ~~^~~~~~~~~~~~~~~~~~
```
replaced by memset.

Fixed complilation error.

---

src/include/player.h
src/map/map_radar.cpp
src/map/mapfield.cpp
src/stratagus/player.cpp
src/unit/unit.cpp

Additional updates to this PR: https://github.com/Wargus/stratagus/pull/287
- Shared vision checking https://github.com/Andrettin/Wyrmgus/commit/2cbc9abb8f70453b602fbd402f5c2d411d26cb5a
- Radar visibility checking https://github.com/Andrettin/Wyrmgus/commit/41115417aece5a876884997acbe5becb61b2bdbc

Improve performance of shared vision and radar visibility.

---

src/game/game.cpp
src/game/trigger.cpp
src/map/script_map.cpp
src/sound/script_sound.cpp
src/stratagus/script_player.cpp
src/ui/script_ui.cpp
src/unit/script_unit.cpp
src/unit/upgrade.cpp

I have added some code examples in some scripts. This can be useful for other map makers.

Added some code examples.

---

po/it.po

I have created an **it.po** file which translates all messages inside the **stratagus.pot** file in Italian

Translated Stratagus messages in Italian

---

po/es.po

Created an **es.po** file. It contains all the texts in the **stratagus.pot** file, translated to Spanish.

Translated all Stratagus messages to Spanish

---

doc/lua/generate_index.py
src/game/game.cpp
src/game/trigger.cpp
src/map/script_map.cpp
src/stratagus/script_player.cpp
src/ui/script_ui.cpp
src/unit/script_unit.cpp
src/unit/script_unittype.cpp
src/unit/upgrade.cpp

This time I have only added few code examples.

Added few code examples

---

src/ai/script_ai.cpp
src/game/game.cpp
src/game/trigger.cpp
src/sound/script_sound.cpp

I'm still adding more code examples. This time I have included some examples related to define a new A.I.

Adding more code examples

---

CMakeLists.txt
cmake/modules/FindSDL2.cmake

Here are some of the changes I had to make in order to get stratagus to build and run on macOS.

Changes for building on macOS.

---

src/map/script_map.cpp
src/unit/script_unit.cpp

I have added some simple code examples that can be shown in the [lua_bindings functions](https://stratagus.com/lua_bindings.html)

Added code examples

---

src/include/fow.h
src/include/map.h
src/map/fow.cpp
src/map/map_fog.cpp
src/map/script_map.cpp

Added third fog type with old renderer for slow machines.
Related PRs:
for wargus: https://github.com/Wargus/wargus/pull/403
for war1gus: https://github.com/Wargus/war1gus/pull/247

Fix for slow rendering of tiled fog of war

---

src/stratagus/script.cpp

now only the LUA debug change as PR

enable LUA debugging

---

.vscode/launch.json
CMakeLists.txt
src/guichan/include/guichan/basiccontainer.h
src/guichan/include/guichan/widget.h
src/guichan/include/guichan/widgets/textfield.h
src/guichan/sdl/sdlinput.cpp
src/guichan/widget.cpp
src/guichan/widgets/container.cpp
src/guichan/widgets/textbox.cpp
src/guichan/widgets/textfield.cpp
src/include/map.h
src/include/net_message.h
src/include/netconnect.h
src/include/stratagus.h
src/include/util.h
src/map/map.cpp
src/network/net_lowlevel.cpp
src/network/net_message.cpp
src/network/netconnect.cpp
src/network/online_service.cpp
src/stratagus/script.cpp
src/stratagus/stratagus.cpp
src/stratagus/util.cpp
src/tolua/network.pkg
src/tolua/ui.pkg
src/ui/interface.cpp
src/ui/widgets.cpp
src/video/font.cpp
src/video/sdl.cpp

This includes a bunch of fixes for crashes when using the online menu. The "big" new feature is auto-download for maps. Doesn't always work, but good enough for maps made with the map editor

Online Gaming Improvements

---

src/network/online_service.cpp

It fixes https://github.com/Wargus/stratagus/issues/386 for me

Changed boolean into bool in online_service.cpp

---

src/action/action_resource.cpp
tools/genversion.cpp

Memleak.genversion

---

src/sound/sound_server.cpp

Build with disabled DYNAMIC_LOAD currently fails due to undeclared ForceLoadSample

Fix build with disabled DYNAMIC_LOAD

---

doc/uml/class/ai.xmi

I started making the UML Class Diagrams of the Stratagus project by using [Umbrello](https://umbrello.kde.org/), which is also the software that can be used to see the diagram in the file.
The aim is to make class diagrams for each folder in the src folder, since the code is structured with folders.
Here is the class diagram only for the [ai](https://github.com/Wargus/stratagus/tree/master/src/ai) folder
I would like to know if doing this can be useful or not.

Making UML Class Diagrams

---

gameheaders/stratagus-game-launcher.h
gameheaders/stratagus-gameutils.h
src/include/iolib.h
src/include/util.h
src/sound/sound_server.cpp
src/stratagus/iolib.cpp
src/stratagus/parameters.cpp
src/stratagus/script.cpp
src/stratagus/stratagus.cpp
src/stratagus/util.cpp
src/video/shaders.cpp

Fixes some code on windows when UNICODE is defined.

Fixes for UNICODE.

---

src/action/action_built.cpp

Builder was dropped **twice** from building(blocking one extra tile invisibly).

Fix wall construction

---

src/video/graphic.cpp

It also fixes the strange mirroring issue with white background on my side.

Simplify resize and flip image code.

---

src/game/trigger.cpp
src/include/actions.h
src/include/animation/animation_ifvar.h
src/include/color.h
src/include/commands.h
src/include/interface.h
src/include/luacallback.h
src/include/map.h
src/include/net_lowlevel.h
src/include/pathfinder.h
src/include/unit.h
src/include/unit_cache.h
src/include/unit_manager.h
src/include/util.h
src/include/vec2i.h
src/missile/missile.cpp
src/network/net_lowlevel.cpp
src/network/xsha1.h
src/stratagus/translate.cpp
src/ui/icons.cpp
src/video/font.cpp
src/video/renderer.h
src/video/sdl.cpp

Replace `typedef` by `using`.

---

src/ai/ai.cpp
src/ai/ai_resource.cpp
src/ai/script_ai.cpp
src/animation/animation.cpp
src/game/game.cpp
src/include/unit_cache.h
src/include/unittype.h
src/include/util.h
src/missile/missile.cpp
src/missile/script_missile.cpp
src/network/net_lowlevel.cpp
src/particle/particlemanager.cpp
src/pathfinder/astar.cpp
src/spell/spell_spawnmissile.cpp
src/spell/spells.cpp
src/stratagus/construct.cpp
src/ui/icons.cpp
src/ui/popup.cpp
src/ui/script_ui.cpp
src/ui/ui.cpp
src/unit/script_unit.cpp
src/unit/script_unittype.cpp
src/unit/unit.cpp
src/unit/unit_draw.cpp
src/unit/unittype.cpp
src/video/cursor.cpp
src/video/font.cpp
src/video/sdl.cpp
src/video/video.cpp
tools/png2stratagus.cpp

Replace some iterator usages by for-range or algorithm.

Replace some iterator usages by for-range or algorithm.

---

src/ai/ai_resource.cpp
src/ai/script_ai.cpp
src/game/game.cpp
src/include/unit_cache.h
src/include/util.h
src/map/fow.cpp
src/map/fow_utils.cpp
src/missile/missile.cpp
src/network/network.cpp
src/particle/particlemanager.cpp
src/pathfinder/astar.cpp
src/stratagus/groups.cpp
src/stratagus/iolib.cpp
src/stratagus/script.cpp
src/stratagus/selection.cpp
src/unit/unit_find.cpp
src/video/video.cpp

Use `ranges`.

---

src/action/action_still.cpp
src/ai/ai_building.cpp
src/ai/ai_force.cpp
src/ai/ai_resource.cpp
src/editor/editloop.cpp
src/game/trigger.cpp
src/include/missile.h
src/include/particle.h
src/include/unit.h
src/include/unit_find.h
src/map/map_draw.cpp
src/missile/missile.cpp
src/missile/missile_flameshield.cpp
src/particle/particlemanager.cpp
src/spell/spell_areaadjustvital.cpp
src/spell/spell_demolish.cpp
src/spell/spell_spawnmissile.cpp
src/spell/spells.cpp
src/stratagus/script_player.cpp
src/stratagus/selection.cpp
src/unit/build.cpp
src/unit/script_unit.cpp
src/unit/unit.cpp
src/unit/unit_draw.cpp
src/unit/unit_find.cpp
src/unit/upgrade.cpp

Replace some output variables as return type.

Replace some output variables as return type.

---

src/video/graphic.cpp

This reverts commit a9210446eb7e5c1e2c5738440dfda6becbea4f2f.
Seems there is an incompatibility SDL issue...

Revert "Simplify resize and flip image code."

---

src/action/action_build.cpp
src/action/action_train.cpp
src/action/action_upgradeto.cpp
src/ai/script_ai.cpp
src/animation/animation_setplayervar.cpp
src/animation/animation_spawnunit.cpp
src/editor/editloop.cpp
src/editor/edmap.cpp
src/game/replay.cpp
src/include/unittype.h
src/include/upgrade.h
src/map/script_map.cpp
src/spell/spell_polymorph.cpp
src/spell/spell_spawnportal.cpp
src/spell/spell_summon.cpp
src/stratagus/player.cpp
src/stratagus/script_player.cpp
src/tolua/unittype.pkg
src/ui/botpanel.cpp
src/ui/mainscr.cpp
src/ui/script_ui.cpp
src/unit/depend.cpp
src/unit/script_unit.cpp
src/unit/script_unittype.cpp
src/unit/unittype.cpp
src/unit/upgrade.cpp

`Unittypebyident` now returns reference instead of pointer (to avoid null deferencing).
Fix one call with `"$(race)-group"`.

Unittypebyident

---

src/game/game.cpp
src/unit/script_unittype.cpp
src/unit/unit_save.cpp
src/unit/unittype.cpp

`printf` format `%s` expects arguments `const char*` and not `std::string`/`std::string_view`).

Fix crash in save:

---

src/include/script.h
src/include/ui.h
src/include/ui/contenttype.h
src/include/video.h
src/ui/contenttype.cpp
src/ui/mainscr.cpp
src/ui/script_ui.cpp
src/ui/ui.cpp

`enum class` for `EnumVariable`.

---

CMakeLists.txt

Improve experimental filesystem CMake Check

---

CMakeLists.txt

Split stratagus source into library and executable, and add UTs in CMake.

Add UTs in CMakeLists.txt

---

src/game/trigger.cpp

introduced by SHA-1: aef070dac6b54e2536b…aae711cdf92bab7ed7c73 (Oct 2nd 2023).

Fix "typo" in `GetNumUnitsAt`

---

src/animation/animation_spawnmissile.cpp

Fix null pointers check

---

src/action/action_built.cpp
src/stratagus/construct.cpp

Add extra checks for construction

Fix `FindCFramePercent`.

---

src/editor/editloop.cpp
src/editor/editor.cpp
src/editor/edmap.cpp
src/include/editor.h
src/tolua/editor.pkg

Remove unused `MapLoaded`/`WriteCompressedMaps`/`PopUpX`/`PopUpY`

Cleanup Editor:

---

src/include/icons.h
src/include/iolib.h
src/include/map.h
src/include/net_message.h
src/include/net_serialization.h
src/include/particle.h
src/include/pathfinder.h
src/include/player.h
src/include/sdl2_helper.h
src/include/settings.h
src/include/sound.h
src/include/spells.h
src/include/st_backtrace.h
src/include/tileset.h
src/include/ui.h
src/include/unit.h
src/include/unitptr.h
src/include/unittype.h
src/include/upgrade_structs.h
src/include/vec2i.h
src/include/video.h
src/include/viewport.h
src/include/wav.h
src/include/widgets.h
src/map/map_draw.cpp
src/network/net_message.cpp
src/particle/graphicanimation.cpp
src/pathfinder/pathfinder.cpp
src/ui/icons.cpp
src/ui/widgets.cpp

- member initializations
- add some missing `const`
- add some missing `explicit`
- `default` some default constructor
- remove declaration without definition `CUpgrade::SetIcon`

Clean up headers:

---

src/action/action_resource.cpp
src/include/unit.h
src/unit/script_unit.cpp
src/unit/unit.cpp
src/unit/unit_find.cpp
src/unit/unit_save.cpp

Savegame is incompatible with previous version

[cleanup] Use `std::vector` for `CUnit::Resource::AssignedWorkers`

---

src/editor/editloop.cpp
src/editor/edmap.cpp
src/include/fov.h
src/include/fow.h
src/include/fow_utils.h
src/include/map.h
src/include/parameters.h
src/map/fov.cpp
src/map/fow.cpp
src/map/fow_utils.cpp
src/map/map.cpp
src/map/map_draw.cpp
src/map/map_fog.cpp
src/map/script_map.cpp
src/map/tileset.cpp

Went through most of the files I've ever worked with, cleaned up the typos. Predominantly my own )

Fixed English typos

---

src/editor/editloop.cpp
src/editor/edmap.cpp
src/include/editor.h

Also:
- Fixed permanent brush application while the left button is pressed.
- A little cleanup has been done to make the conditional statements a bit clearer.

Restored broken "alt+click" edit tile mode.

---

src/include/video.h

[bugfix] Fix some endianess issues
