Wargus/stratagus

src/include/parameters.h
src/include/script.h
src/network/netconnect.cpp
src/stratagus/iolib.cpp
src/stratagus/script.cpp
src/stratagus/stratagus.cpp

This is related to https://github.com/Wargus/wargus/issues/132, as this allows us to handle commandline arguments in lua scripts. This commit also makes the script searching a little more clever, so we could conceivably have lua scripts in the user directory that then handle arguments and run the game.

Allow passing a string as argument to the Lua startup file

---

src/include/tileset.h
src/map/map_wall.cpp
src/map/tileset.cpp

I wpuld like to use this for war1gus, where dungeon doors are destructible like walls, but they dont have all the possible directions. @Andrettin, you have dungeons in Wyrmsun, too, do you think this looks ok, or might it break something?

For incomplete wall tilesets, keep the current directionality if the new direction is missing

---

COPYING

Fixes the following rpmlint warning:
```
W: incorrect-fsf-address /usr/share/doc/packages/wyrmgus/COPYING
The Free Software Foundation address in this file seems to be outdated or misspelled.
Ask upstream to update the address, or if this is a license file, possibly the entire file with a new copy available from the FSF.
```

Fixed FSF address in license text

---

src/include/unittype.h
src/unit/script_unittype.cpp
src/unit/unit_find.cpp

Prompted by https://github.com/Wargus/war1gus/issues/63, I looked at the code for target finding when we have a missile with splash damage. In Warcraft 1, catapults simply will not fire if there is a chance it might hurt friendly units (even if they would survive). Stratagus seems to use a cost-weighing function that accepts friendly fire, and only slightly prefers to attack units that are not near friendly units if possible.
I refactored this code to be slightly more explicit, and I added a FriendlyFire flag (by default set to true) that determines if we want Warcraft 1 type behavior for a unit type. I don't want to merge this without some feedback, so that's why the pull request

Refactor target searching for splash missiles to make friendly fire configurable

---

gameheaders/stratagus-game-launcher.h

It was not able to find the file because of the backslash notation.
Use slash notation on non Windows systems to fix it.

Fix test for data extraction on non Windows system

---

src/unit/unittype.cpp

This change is needed for War1gus. In War1gus, you should be able to build directly over roads. One way to do this would be to make them decorations but not buildings, but then you can built them on map tiles marked with `no-building`. This solution makes roads be buildings again, but since they do not have HP, they _can_ be built over. If there are no objections to this, I'll merge this later tonight.

Allow building over decorative buildings without HP

---

src/include/shaders.h
src/ui/interface.cpp
src/video/png.cpp
src/video/shaders.cpp

This doesn't rely on the internal organization of std::vector as an array and accounts for shader support as well as possibly different Viewport sizes vs Video sizes. Should fix #156 and might help with https://github.com/Andrettin/Wyrmgus/issues/73

Fixes for screenshot code with opengl

---

doc/changelog.html
doc/development.html
doc/faq.html
doc/graphics/palette.html
doc/graphics/tileset.html
doc/index.html
doc/install.html
doc/media.html
doc/scripts/ai.html
doc/scripts/config.html
doc/scripts/game.html
doc/scripts/index.html
doc/scripts/magic.html
doc/scripts/mappresentation.html
doc/scripts/mapsetup.html
doc/scripts/research.html
doc/scripts/savegame.html
doc/scripts/sound.html
doc/scripts/tileset.html
doc/scripts/triggers.html
doc/scripts/ui.html
doc/scripts/unittype.html

Fixed FSF address in documentation.
See also [gnu.org](https://www.gnu.org/licenses/old-licenses/gpl-2.0#SEC4).
Without this fix this leads into a lot of RPMLint warnings when building for openSUSE.

Fixed FSF address

---

src/ai/ai_force.cpp

I get an AccessViolation without this fix. It seems to me that it doesn't make sense to use force.GoalPos after force.ReturnToHome has been called since it's set to -1/-1

Don't use AIForce's GoalPos after calling ReturnToHome()

---

src/map/minimap.cpp

https://github.com/Wargus/wargus/issues/266
Seen buildings did not get removed from minimap when destroyed while under fog of war.
Test:
Create a map in the editor where one computer has some farms, another has grunts and you have a zeppelin.
Play the map in free for all, with fog of war enabled.
Scout out the farm, then pull away and wait for the grunts to finish it.
After some time the farms are removed from the main view.
(And with this patch, they are removed from the minimap as well).

Fix issue #266 in wargus, Minimap not updated after buildings destroyed

---

src/ui/mouse.cpp

https://github.com/Wargus/wargus/issues/193
This allows clicking on a unit icon (portrait) to cast a spell.
Test:
Get 2 paladins that know the healing spell.
Make sure one is wounded.
Select both of them.
Click healing or the H button.
Select the wounded paladin from the left toolbar (instead of clicking on the main map).
The wounded paladin should be healed.
I'm new, please be nice :-)

Fix issue #193 in wargus, Casting on unit portraits

---

src/action/action_attack.cpp

https://github.com/Wargus/wargus/issues/175
Allows autocast to trigger during an attack-move.
(I assume this to mean anytime the unit has the attack order, but not actually attacking something.)
Perhaps it must be configurable?
And should it also trigger while attacking?
Or should it not trigger when you target attack a unit?

enable autocast during attack-move

---

src/action/action_built.cpp
src/action/action_move.cpp
src/include/missile.h
src/include/sound.h
src/map/map.cpp
src/map/minimap.cpp
src/missile/missile.cpp
src/sound/sound.cpp
src/unit/unit_draw.cpp
src/video/sdl.cpp

* Don't let pointtopoint missiles wobble
* Don't spam "Game Resumed" from SDL
^ On my laptop, I kept getting "Game Resumed" popping up on the status bar.
* Hack to make mana visible for units on bottom row
* Play transport docking sound more reliably
* Play random building noises
* Don't show wood being cut under fog of war
* Fix wood not updated by ally vision
* Fix "revealer unit" visible on minimap when casting holy vision in wargus.
* Fix missile not targeting center of 2x2 and 4x4 units.

Various small ui/gfx/sound fixes

---

src/action/action_resource.cpp
src/action/actions.cpp
src/ui/botpanel.cpp
src/ui/mouse.cpp

Previously, it was possible to tell a unit to return goods with the terrain-harvester trait before it reached full capacity.
The effect was that the terrain was left intact and the worker would return what it had mined so far.
Thus you could get unlimited amount of resources from the same terrain tile (we don't track resources in terrain).
Also partially implemented the 'lose-resources' trait. I'm not exactly sure how it's supposed to work, but now kinda does what it says it should do in comments/doc.
Perhaps it should also be triggered in COrder_Resource::LoseResource ..?
But, then we might need to develop the terrain-harvester some more first. (workers cut the same tree in wargus, in original they try hard to spread out).

fixes for terrain-harvester and maybe lose-resources

---

src/ui/mainscr.cpp

Hey guys.
Using gcc version 7.4.0 I get a warning in CInfoPanel::Draw() in src/ui/mainscr.cpp when building in release configuration. Anybody else having that problem?
_stratagus/src/ui/mainscr.cpp:1168:6: error: ‘%lu’ directive writing between 1 and 20 bytes into a region of size 5 [-Werror=format-overflow=]_
Increasing the buffersize to 22 solves the problem for me.
Regards
David

Increase buffersize due to possible overflow

---

src/network/net_lowlevel.cpp

`if (ifa->ifa_flags & IFF_UP == 0) continue;`
== has higher priority than &

Fix condition check

---

src/missile/missile.cpp

Now missiles spawn in the center of **unit**, not in the center of the unit's **map tile**. For units larger than 1x1 tile that looked weird - missile launches from top left tile.
Offset (if needed for fine tuning) must be set in the units declaration lua-files by MissileOffsets = {}.
There was PR https://github.com/Wargus/wargus/pull/307 which moved origin point for towers to their center. It added {16,16} offset to Stratagus calculated center for 32x32 map tile where the unit are, as a result we had origin poinf for missiles at bottom right corner of upper left tile - exactly center of 2x2 tile tower. But, these offsets was added for other units too, and broke their missile origin points - they are moved to the right and down.

Missiles spawn position fix. Moved to the center of unit.

---

src/network/netconnect.cpp

There is an issue with connecting to network game - client rejected to connect if selected map contains spaces in it's path/file_name. 
This allow spaces in the map's filenames.

Allow spaces in the maps filenames for network games.

---

src/video/graphic.cpp

@Andrettin :
>There are two issues there
first, the lack of parenthesis was making only the "j" (= X) be multiplied by the BPP, instead of the whole "i * Width + j" as would make sense
And two, since the pointer is to an uint32 (4 bytes), instead of a type that has a single byte, it shouldn't be multiplied by the BPP at all

Fixed issue with grayscale application for BPP 4.

---

src/action/action_attack.cpp
src/action/action_still.cpp
src/action/actions.cpp
src/include/action/action_attack.h
src/include/pathfinder.h
src/include/unit.h
src/include/unittype.h
src/pathfinder/astar.cpp
src/pathfinder/pathfinder.cpp
src/tolua/unit.pkg
src/unit/script_unittype.cpp
src/unit/unit.cpp
src/unit/unit_find.cpp

There were some problems with automatic target selection. 
- After receiving attack-move order attacker chose a target and may fixing on it, even if a higher priority target is appeared nearby. F.e. attacker may beat barracks and don't switch to the appeared from it new enemy unit, or may attack farms, but do not switch to peons nearby.
- Unit being under attack by tower, may attack farm, and do not switch target, as result - die.
- etc.
Maybe that wasn't a big problem for single player and campaign, but for multiplayer game that was terrible. 
What was done. 
1. Was made some fixes in original code, now units don't fixed on once selected target when in auto attack mode. Made some refactoring.
2. As an option was implemented [starcraft 2 automatic targeting …

Automatic Targeting.

---

src/action/action_move.cpp

Units in the action-move will not finish action if any unit come to their goalPos-tile, or being build on it. They will stay on the neighbour tile inactive (actually it will be in permanent waiting state initiated by `DoActionMove()`).
This PR added additional check for `DoActionMove()` result, and will finish action if aforementioned event occurs.

Fix issue with unfinishable action-move.

---

src/ai/ai_resource.cpp

Previously the AI would cheat if instructed to upgrade city hall before it could with AiUpgradeTo.
Land/Sea/Air AI still works with this patch at least.. didn't test campaign.

check dependencies for ai when upgrading

---

src/action/command.cpp
src/include/player.h
src/include/unit.h
src/map/map_fog.cpp
src/map/map_radar.cpp
src/map/mapfield.cpp
src/stratagus/player.cpp
src/stratagus/script_player.cpp
src/tolua/player.pkg
src/ui/mouse.cpp
src/unit/unit.cpp

@Andrettin:
>I just made a change that resulted in the visibility-checking code becoming a lot faster
when checking for visibility of a unit or tile.
Instead of looping through ALL players and checking if each has shared vision with the "this" player and if they see the unit.
I made shared vision be stored in the player instance as a set of player indexes. So then I just iterate over the other players the player actually has shared vision with.
This is specially important for when moving the mouse, because
when you move the mouse, it checks to see if ALL units are visible and on the viewport
Original commit: https://github.com/Andrettin/Wyrmgus/commit/ac15658ec515cfc7bb8e723961d066a3a6cb17ae
There is two corresponding PRs:
For wargus: https://github.com/Wargus/wargus/pull/326
For war1gus: …

Improved the performance of the shared vision code.

---

.travis.yml
appveyor.yml
src/action/action_build.cpp
src/include/player.h
src/include/unittype.h
src/map/map_fog.cpp
src/map/mapfield.cpp
src/map/minimap.cpp
src/stratagus/player.cpp
src/stratagus/script_player.cpp
src/unit/script_unittype.cpp
src/unit/unit.cpp

Units of revealed players will appear in the minimap. 
Mostly need in the end of game, in cases when enemy units spread out across map and you have to find all of them to finish this game.
If enabled, there is two options "Reveal all units" (set by default) and "Reveal only buildings" (added for future use). Which can be selected in the stratagus.lua by calling `SetRevelationType()`.
Loosing last Town Hall triggered timer, an if player will not start build another TH he will be revealed.

Add units revelation for players, which had lost their last Town Hall.

---

src/stratagus/player.cpp

Because of C++11's enum class doesn't guarantee contiguous values (unlike C++03's enum) this condition check has no sense.

Removed wrong enum class values comparation.

---

src/stratagus/iolib.cpp

hFile should be defined as intptr_t to resolve 0xC0000005: Access Violation in ntdll.dll, as per https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/findnext-functions?redirectedfrom=MSDN&view=vs-2019

Fixed Access Violation on Windows 10 (x64)

---

src/unit/script_unit.cpp

I was playing around with the <u>Wargus editor</u> and I found a specific Lua script where I can specify some orders to give to the units inside the <u>.sms</u> files. So I was searching for the commands **stop** and **stand-ground** but every time I tried to give those orders I got this error:
`/build/stratagus-A5HbDh/stratagus-3.0.0/src/unit/script_unit.cpp:870: CclOrderUnit: Unsupported order: stand-ground`
So I have found the commands inside the **commands.cpp** file and I simply added these two commands in the **CclOrderUnit** static function.

Adding two commands in CclOrderUnit

---

src/map/script_map.cpp

From the [issue](https://github.com/Wargus/stratagus/issues/318) I have written today the problem of why the function ShowMapLocation don't work it's because the number of arguments passed through LuaCheckArgs were 4 instead of 5 like it is indicated in the [documentation](https://htmlpreview.github.io/?https://raw.githubusercontent.com/Wargus/stratagus/master/doc/scripts/game.html#ShowMapLocation).

Fixed the LuaCheckArgs in CclShowMapLocation

---

gameheaders/stratagus-game-launcher.h
src/video/sdl.cpp

Fixing issue https://github.com/Wargus/wargus/issues/372 to make Stratagus work on Windows Seven (including the 32bits version).
Must be strarted with `-g -W` flags to not use OpenGL and have a Window.
Also fixing some crashes because using unintialized string buffer.

Fix372 win7

---

gameheaders/stratagus-game-launcher.h
src/network/net_lowlevel.cpp
src/ui/widgets.cpp

In mission briefing (or possibly anywhere else), there is no need to render empty strings.

Add optimization to not draw text when text is empty 

---

.gitignore
CMakeLists.txt

Building SDL2 from source on macOS doesn't produce a dynamic library for libSDL2main.  Similarly installing SDL2 through macports only installs libSDL2main.a.  The first commit solves the issue with linking to SDL2main. 
The second commit adds .DS_Store to .gitignore to avoid file pollution.

Minor fixes for macOS. Fix linker error with libSDL2main. Add .DS_Store to .gitignore.

---

CMakeLists.txt

- Use `CMAKE_<LANG>_COMPILER_ID` to detect compiler as CMake docs suggest
- Support clang properly
- Don't set -Werror (see https://amdmi3.ru/posts/packaging-friendliness-compiler-flags-to-avoid/)

Fix compiler detection and flags

---

CMakeLists.txt

This ensures correct include ordering and hides warnings coming from unrelated code. Specifically, it fixes build on FreeBSD, which otherwise fails due to to problem in lcms code:
In file included from .../stratagus-3.3.1/src/action/action_defend.cpp:45:
In file included from .../stratagus/work/stratagus-3.3.1/src/include/ui.h:56:
In file included from .../stratagus-3.3.1/src/include/viewport.h:34:
In file included from .../stratagus-3.3.1/src/include/fow.h:39:
In file included from .../stratagus-3.3.1/src/include/video.h:228:
In file included from /usr/local/include/libmng.h:385:
In file included from /usr/local/include/libmng_types.h:181:
/usr/local/include/lcms.h:1238:29: error: ISO C++17 does not allow 'register' storage class specifier [-Wregister]
typedef int (* …

Add header paths for system libraries as SYSTEM

---

tools/genversion.cpp

Allow to override build date with `SOURCE_DATE_EPOCH`in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good and https://reproducible-builds.org/specs/source-date-epoch/ for the definition of this variable.
This patch was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).

Allow to override build date with SOURCE_DATE_EPOCH

---

src/map/map_draw.cpp

There are  few map reveal modes (known and explored) which works with tiled (not legacy) fog type too, so we have to check map reveal mode instead of fog type here.

Fixed broken map rendering in cases when map is revealed

---

src/map/map_draw.cpp

After all, it turns out that you have to switch off this optimization for enhanced fog too.

Additional fix for broken map rendering in cases when map is revealed.

---

src/video/font.cpp

For some reason that I can't understand (I have no knowledge in graphic surfaces) this check fails for `large` font created by wargus's wartool from russian `SPK` Warcraft II version.
After applying fix for russian translation [1] I found that some letters are missing from words, however they are presented in translation strings.  
Debugging this issue I found that `CFont::CharWidth` have no data for those letters.
I added printf() here and the cycle was stopped at y=196, with gp less than 255, however all letters before 196 had gp=255.
After removing this check I got values:
```
CFont::MeasureWidths: large: y: 194: sp: 255, gp: 255
CFont::MeasureWidths: large: y: 195: sp: 0, gp: 0
CFont::MeasureWidths: large: y: 196: sp: 255, gp: 0
CFont::MeasureWidths: large: y: 197: sp: 255, gp: 125 …
```

video: font: fixed glyph last pointer calculation 

---

src/include/unit_find.h

Silences the following compiler warning. Was previously being called 33 times: 
```
warning: use of logical '||' with constant operand [-Wconstant-logical-operand]
int max = selectMax || INT_MAX;
^  ~~~~~~~
note: use '|' for a bitwise operation
```
Someone with better C++ skills than me should review to make sure functionality remains the same.

Silence warnings: Change a logical || to a bitwise |

---

gameheaders/stratagus-game-launcher.h
src/stratagus/parameters.cpp

Stratagus currently puts data files in `~/Library/Stratagus`, but it should use `~/Library/Application\ Support/Stratagus`
I have tested this using my previously installed game data. After building with these changes, I moved the Stratagus folder into Application Support and was able to launch Wargus through the command line as usual. 
I have not tested with Wartools to see if it extracts data correctly. That will need to be tested before merging.

Requires Testing - [macOS] Use the Application Support folder for game data

---

.github/workflows/appimage.yml

Fix github action node warning:
-- 8< --
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/checkout@v2. For more info: https://github.blog/changelog/2023-06
-- >8 --

Fix github action node warning:

---

src/include/unittype.h

quick fix for:
In file included from /usr/include/X11/Xlib.h:44,
from /usr/include/SDL2/SDL_syswm.h:69,
from /home/andreas/src/git/stratagus/stratagus/src/video/sdl.cpp:58:
/home/andreas/src/git/stratagus/stratagus/src/include/unittype.h:510:9: error: expected identifier before numeric constant
510 |         None = 0, /// Nothing
|         ^~~~
/home/andreas/src/git/stratagus/stratagus/src/include/unittype.h:510:9: error: expected ‘}’ before numeric constant
In file included from /home/andreas/src/git/stratagus/stratagus/src/include/unit.h:43,
from /home/andreas/src/git/stratagus/stratagus/src/video/sdl.cpp:79:
/home/andreas/src/git/stratagus/stratagus/src/include/unittype.h:509:1: note: to match this ‘{’
509 | {
| ^
In file included from /usr/include/X11/Xlib.h:44,
from …

quick fix for a define on Linux

---

src/action/actions.cpp
src/include/actions.h
src/ui/botpanel.cpp
tools/build_appimage.sh

1. Renamed UnitAction::None to ::NoAction because of conflict with 'None' macros defined in sdl.h (https://github.com/Wargus/stratagus/pull/515)
2. Also changed ICONDIR for appimage (https://github.com/Wargus/stratagus/issues/557) to fix linuxdeploy

Fix linuxdeploy and compilation

---

src/ai/script_ai.cpp
src/stratagus/iolib.cpp

- `std::make_unique<T>()` != `std::unique_ptr<T>()`.
- `CFile::printf` now longer print extra nul characters.

Fix typo/regressions:

---

src/include/viewport.h
src/map/map_draw.cpp
src/map/script_map.cpp

The option is used for debugging purposes and was activated together with enabling the map grid. It was a bit annoying. 
This separates them into two independent options.
Now can be toggled with `SetHighlightPassability(true/false)` from lua (incl. `eval` chit code)

Separate highlights of AStar passability from the enable map grid option.

---

src/include/widgets.h
src/tolua/ui.pkg
src/ui/widgets.cpp

- Fix 'browser': `gcn::Widget::addActionListener` is no longer `virtual`, do the dispatch manually.
- Use fixed patched guichan (about button)

Fix guichan

---

CMakeLists.txt

Otherwise it falls back to the global BUILD_SHARED_LIBS that might be set to ON. In that case stratagus_lib.so or stratagus_lib.dll are built.
Makes it consistent to all other libs (from third-party).
submodule third-party containing PR https://github.com/Wargus/dependencies/pull/2 should also be included.

Build libs as static libraries

---

CMakeLists.txt

find_package need to be done before using the variables. e.g. TOLUA++_APP
Fixes https://github.com/Wargus/stratagus/issues/443

Move find_package for lua to correct location

---

src/video/font.cpp

[Fix]
Add missing `break` in `switch`.
[Clean up]
Replace hard coded value `48` by `'0'`.
Move `FormatNumber` at top of file.
`CFont::Width` uses directly `FormatNumber`.

small changes in font.cpp

---

src/unit/unit.cpp

Reported by valgrind:
```
==3108== Conditional jump or move depends on uninitialised value(s)
==3108==    at 0x1EC37A: COrder_Still::Execute(CUnit&) (action_still.cpp:424)
==3108==    by 0x1EF361: HandleUnitAction (actions.cpp:449)
==3108==    by 0x1EF361: UnitActionsEachCycle (actions.cpp:574)
==3108==    by 0x1EF361: UnitActions() (actions.cpp:623)
==3108==    by 0x295B9C: GameLogicLoop (mainloop.cpp:268)
==3108==    by 0x295B9C: SingleGameLoop (mainloop.cpp:377)
==3108==    by 0x295B9C: GameMainLoop() (mainloop.cpp:413)
==3108==    by 0x21798F: StartMap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) (game.cpp:146)
==3108==    by 0x302F90: tolua_stratagus_StartMap00(lua_State*) (tolua.cpp:1107)
==3108==    by 0x48A9F4D: luaD_precall …
```

Initialize CUnit::JustMoved in CUnit::Init()

---

src/include/color.h
src/include/font.h
src/tolua/video.pkg
src/video/font.cpp

Should fix issue #596 with font display

Change `CColor` to be opaque (alpha=255) instead of transparent

---

src/include/pathfinder.h
src/pathfinder/pathfinder.cpp
src/unit/script_unit.cpp
src/unit/unit_save.cpp

Fix memory issues at save and load.
Saving a too long path stores no path at all (=an empty path). Loading a too long path also sets it to empty (to be compatible to old saved files).
I hope this is good.
It also fixes the value of Length at runtime.
Resolves https://github.com/Wargus/stratagus/issues/610
It might resolve some of the open crash-issues.

Pathfinder: Fix out-of-bounds read/write at load/store of games

---

src/game/trigger.cpp

Fix some load/save issues with triggers
Fixes:
* Load will create the original number of triggers (not doubled)
* Load: No bad memory access checking for removed triggers
* Load: removed triggers are now really removed
* Save: The removed-status is correctly saved even if it was from loading a file

Fix some load/save issues with Triggers

---

CMakeLists.txt
src/game/trigger.cpp
tests/stratagus/test_trigger.cpp

Run all check-functions of all triggers in each cycle. Also improve the API of the called functions to get the index of the trigger [0,n-1] instead of an (shifted) index into a lua-table of triggers.
Contrary to the documentation [1] only one trigger condition is run in every Cycle. This state is even saved to a saved game file.
[1] https://github.com/Wargus/stratagus/blob/838f82ec7f31234933c9f999150e17b59c754057/src/game/trigger.cpp#L412-L416

Check each trigger-condition in each cycle

---

tests/stratagus/test_depend.cpp
tests/stratagus/test_trigger.cpp

Depend: Fix test error with randomized order (unittype not existing).
Depend: Fix memory leaks.
Trigger: Fix Let tests work with randomized order (GamePaused is not initialized to false).
Trigger: Add more tests of Actions.

Make unittests more robust

---

CMakeLists.txt
src/include/missile.h
src/include/util.h
src/missile/missile.cpp
src/missile/script_missile.cpp
tests/stratagus/test_missile_fire.cpp

Burning animation disappears before building is completely destroyed.
Fix and add unittest.
Simplify storage a bit.
Comment: Percent logic is similar to construction. Code could be combined.
State before:
Burning at 6/400=1.5%:
No longer burning at 2/400=0.5%:

Fix glitch of burning building animation

---

src/include/cursor.h
src/include/sdl2_helper.h
src/video/cursor.cpp

Use `sdl2::SurfacePtr` in `CCursor`.
Add `sdl2::CursorPtr`.

smart pointer in CCursor

---

CMakeLists.txt

Fixes:
* Some warnings of cmake.
* A dependency issue with the generated version-generated.h file: Dependent files have not been rebuilt at first call of ninja.

Fix cmake warnings

---

CMakeLists.txt
src/action/action_built.cpp
src/include/action/action_built.h
tests/stratagus/test_action_built.cpp

Testing the percentage lookup code fixed some days ago.
TODO: What else to test in here? and how?

Action_built: Add unittest for percentage lookup

---

src/editor/editloop.cpp
src/include/net_message.h
src/include/settings.h

That should ensure that `uintXX_t` is (also) in namespace `std`.

Replace C-header `<stdint.h>` by C++-header `<cstdint>`.

---

src/include/interface.h

Fix typo: `ScrollRightDown = ScrollRight | ScrollLeft` -> `ScrollDown | ScrollLeft`.
closes #682

[bugfix] edge scroll (down+right only) broken

---

src/include/cursor.h

add missing include statement into `src/include/cursor.h`:
```c
#include <string>  // new line
```

add missing <string.h>; fixes #688

---

src/include/title.h
src/stratagus/title.cpp
src/ui/script_ui.cpp

```
SetTitleScreens(
{Image = "ui/title.png", StretchMode = "none"}, -- Keep original image size
{Image = "ui/title.png", StretchMode = "keep-ratio"}, -- resize to touch border, and keep original size ratio
{Image = "ui/title.png", StretchMode = "stretch"} -- (default) resize to the full windows
)
```

Allow to define stretch mode to title screen:

---

src/action/action_move.cpp
src/pathfinder/pathfinder.cpp
tests/stratagus/test_pathfinder.cpp

close https://github.com/Wargus/war1gus/issues/455

Doactionmove war1gus

---

CMakeLists.txt
src/include/stratagus.h
tests/stratagus/test_format.cpp

This fixes broke game save
The beginning of a broken saved game looks like this:
```
$ zcat ~/.config/stratagus/wc2/save/game.sav.gz|xxd -C|head -5
00000000: 6c6f 6361 6c20 6f6c 6443 7265 6174 6555  local oldCreateU
00000010: 6e69 7420 3d20 4372 6561 7465 556e 6974  nit = CreateUnit
00000020: 006c 6f63 616c 206f 6c64 5365 7452 6573  .local oldSetRes
00000030: 6f75 7263 6573 4865 6c64 203d 2053 6574  ourcesHeld = Set
00000040: 5265 736f 7572 6365 7348 656c 6400 6c6f  ResourcesHeld.lo
```
The newlines are replaced by null-characters so games could not be loaded again.

Fix Format function to not cut of last character (fixes game save)

---

src/include/unit_manager.h
src/unit/unit_manager.cpp

This reverts commit c8ff12112548e95e7eca85d69a1a385085b33e7f.
Crash with typo with `unit->UnitManagerData.slot = unitSlots.size() - 1;`.
but also destruction all unit cause a crash with destruction order, so revert back to memory leak.

Revert "[cleanup] Use `std::unique_ptr` for `unitSlots`."

---

.github/workflows/macos.yml

Removes: 
- Dylibbundler: This is used when making app bundles, not needed here
- Meson: This is used for compiling Stargus
- Libpng: It is already installed in the runner
Also removes two duplicated lines.

CI: Remove unnecessary dependencies from macOS CI

---

src/editor/editloop.cpp
src/editor/edmap.cpp
src/include/editor.h
src/include/tileset.h
src/map/tileset.cpp

To set current single tiled type brush with a tile not from tile icons palette, but from any map field under cursor you should:
1. reset selected tile (right click)
2. ctrl+left click on the any tile within map grid.

Added tool to set a brush tile with picked one from the map.

---

src/ai/ai_local.h

comparison with `-1` is now correct in `getScriptForce` (even when `char` is `unsigned`).
fixes #739

[fix] Change type of `AiForceManager::script`
